# Generated by Django 4.1.7 on 2023-03-05 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категориялар',
                'verbose_name_plural': 'Категориялар',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('brand', models.TextField(blank=True, verbose_name='Бренд аты')),
                ('content', models.TextField(blank=True, verbose_name='Сипаттамасы')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Сурет')),
                ('price', models.CharField(max_length=255, verbose_name='Бағасы')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыт')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Өзгертілген уақыт')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикациясы')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='honey.category', verbose_name='Категориясы')),
            ],
            options={
                'verbose_name': 'Продуктілер',
                'verbose_name_plural': 'Продуктілер',
                'ordering': ['time_create', 'name'],
            },
        ),
    ]
