# Generated by Django 4.1 on 2023-04-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("honey", "0002_alter_product_options_product_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bailanys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Аты")),
                ("email", models.CharField(max_length=255, verbose_name="Пошта")),
                (
                    "phone",
                    models.CharField(max_length=255, verbose_name="Телефон нөмір"),
                ),
                ("date", models.CharField(max_length=255, verbose_name="Күні")),
            ],
            options={
                "verbose_name": "Байланыс",
                "verbose_name_plural": "Байланыс",
                "ordering": ["id"],
            },
        ),
    ]
