# Generated by Django 4.1 on 2023-05-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("honey", "0003_bailanys"),
    ]

    operations = [
        migrations.CreateModel(
            name="New",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255, verbose_name="Пошта")),
            ],
            options={
                "verbose_name": "Қосылулар",
                "verbose_name_plural": "Қосылулар",
                "ordering": ["id"],
            },
        ),
        migrations.AlterModelOptions(
            name="bailanys",
            options={
                "ordering": ["id"],
                "verbose_name": "Байланыстар",
                "verbose_name_plural": "Байланыстар",
            },
        ),
        migrations.RemoveField(model_name="bailanys", name="date",),
        migrations.RemoveField(model_name="bailanys", name="phone",),
        migrations.AddField(
            model_name="bailanys",
            name="content",
            field=models.CharField(default=1, max_length=255, verbose_name="Қосымша"),
            preserve_default=False,
        ),
    ]
